version: "3"

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - "5432:5432"
    volumes:
      - ./container/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.env.docker
    ports:
      - "5050:80"
    depends_on:
      - postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./.env.docker
    depends_on:
      - postgres
volumes:
  postgres_data:
